error: optimize(f = f, interval = interval, maximum = maximum, tol = tol) : \n  'xmin' not less than 'xmax' therefore add/substract a small number to the upper and lower bound.
choosing nsub  = 1, otherwise error
Error in if (mult * res$objective < mult * best$objective) best = res :
missing value where TRUE/FALSE needed
In addition: Warning message:
In optimize(f = f, interval = c(grid[j], grid[j + 1L]), maximum = maximum, :
NA/Inf replaced by maximum positive value